pipeline:
  test:
    image: x3enos/ruby-node-2-4-4
    environment:
      - RAILS_ENV=test
    commands:
      - cp docker/drone/database.drone.yml config/database.yml
      - cp docker/drone/drone.env .env
      - bundle install --path=/tmp/bundler --retry=5 --jobs=5
      - bundle exec rspec spec
    volumes:
     - /tmp/bundler:/tmp/bundler
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
