pipeline:
  test:
    image: x3enos/ruby-node-2-4-4
    environment:
      - RAILS_ENV=test
    commands:
      - cp docker/drone/drone.env .env
      - bundle install --path=/tmp/bundler --retry=5 --jobs=5
      - bundle exec rspec spec
    volumes:
     - /tmp/bundler:/tmp/bundler
     - /root/drone_rsa:/root/ssh/drone_rsa
     
  docker:
    image: plugins/docker
    repo: x3enos/expenses_tracker_bot
    tags: ${DRONE_COMMIT_BRANCH}
    secrets: [ docker_username, docker_password ]

  ssh:
    image: appleboy/drone-ssh
    host: 151.236.216.234
    username: dockeradmin
    volumes:
      - /root/drone_rsa:/root/ssh/drone_rsa
    key_path: /root/ssh/drone_rsa/id_rsa
    command_timeout: 300
    script: BUILD_ID=${DRONE_COMMIT_BRANCH} ./stage_launch.sh

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=expensestrackerbot_test
