default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: expensestrackerbot_development

test:
  <<: *default
  database: expensestrackerbot_test

production:
  <<: *default
  host: ENV["DB_CONTAINER_NAME"]
  database: expensestrackerbot_production
